### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by sikmike** [scottlepp/go-duck#22]
Hi,

very nice idea. I wonder do you have any benchmarks comparing your wrapper / cli performance and marcboeker/go-duckdb?

**Comment by scottlepp** [comment]
Hi @sikmike,

I don't have performance benchmarks.  marcboeker/go-duckdb requires CGO which is a show stopper for some folks, my current company in particular.

Also, there are 2 modes.  One runs in docker.  So performance will vary based on the mode and docker config.

It's probably similar to comparing the go driver vs the cli performance.  Not sure if there are benchmarks somewhere for that but since the cli is written in c++ I would assume it's faster.
